// Mock data for courses
export const courseListings = [
    {
        id: 1,
        slug: "complete-airbnb-hosting",
        title: "Khóa Học Toàn Diện về Kinh Doanh Airbnb",
        instructor: "Nguyễn Văn A",
        price: "2,990,000",
        duration: "8 weeks",
        image: "/images/courses/airbnb-hosting.jpg",
        students: 1234,
    },
    {
        id: 2,
        slug: "airbnb-photography",
        title: "Chụp Ảnh Chuyên Nghiệp cho Airbnb",
        instructor: "Nguyễn Việt Anh",
        price: "1,490,000",
        duration: "4 weeks",
        image: "/images/courses/photography.jpg",
        students: 856,
    },
    {
        id: 3,
        slug: "airbnb-interior-design",
        title: "Thiết Kế Nội Thất cho Airbnb",
        instructor: "Lê Văn C",
        price: "2,490,000",
        duration: "6 weeks",
        image: "/images/courses/interior-design.jpg",
        students: 945,
    },
    {
        id: 4,
        slug: "airbnb-business-management",
        title: "Quản Lý Kinh Doanh Airbnb Hiệu Quả",
        instructor: "Phạm Thị D",
        price: "3,490,000",
        duration: "10 weeks",
        image: "/images/courses/business-management.jpg",
        students: 678,
    },
    {
        id: 5,
        slug: "airbnb-marketing",
        title: "Marketing cho Airbnb",
        instructor: "Hoàng Văn E",
        price: "1,990,000",
        duration: "5 weeks",
        image: "/images/courses/marketing.jpg",
        students: 1023,
    },
    {
        id: 6,
        slug: "airbnb-customer-service",
        title: "Kỹ Năng Chăm Sóc Khách Hàng",
        instructor: "Vũ Thị F",
        price: "1,490,000",
        duration: "4 weeks",
        image: "/images/courses/customer-service.jpg",
        students: 567,
    },
]; 